<?php

namespace Ahs\DemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Ahs\DemoBundle\Entity\User
 *
 * @ORM\Table(name="User")
 * @ORM\Entity
 */
class User
{
    /**
     * @var integer $usrId
     *
     * @ORM\Column(name="usr_id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $usrId;

    /**
     * @var string $usrGivenname
     *
     * @ORM\Column(name="usr_givenname", type="string", length=255, nullable=false)
     */
    private $usrGivenname;

    /**
     * @var string $usrFamilyname
     *
     * @ORM\Column(name="usr_familyname", type="string", length=255, nullable=false)
     */
    private $usrFamilyname;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     *
     * Make sure the jointable name uses right case on Mac an Linux!
     *
     * @ORM\ManyToMany(targetEntity="Address", inversedBy="usr", cascade={"persist"})
     * @ORM\JoinTable(name="User_has_Address",
     *   joinColumns={
     *     @ORM\JoinColumn(name="usr_id", referencedColumnName="usr_id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="adr_id", referencedColumnName="adr_id")
     *   }
     * )
     */
    private $adr;

    /**
     * NOT GENERATED BY DOCTRINE
     *
     * @var \Doctrine\Common\Collections\ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Email", mappedBy="user", cascade={"persist"})
     */
    private $emails;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->adr    = new \Doctrine\Common\Collections\ArrayCollection();
        $this->emails = new ArrayCollection(); // NOT GENERATED BY DOCTRINE
    }

    /**
     * Get usrId
     *
     * @return integer
     */
    public function getUsrId()
    {
        return $this->usrId;
    }

    /**
     * Set usrGivenname
     *
     * @param string $usrGivenname
     * @return User
     */
    public function setUsrGivenname($usrGivenname)
    {
        $this->usrGivenname = $usrGivenname;

        return $this;
    }

    /**
     * Get usrGivenname
     *
     * @return string
     */
    public function getUsrGivenname()
    {
        return $this->usrGivenname;
    }

    /**
     * Set usrFamilyname
     *
     * @param string $usrFamilyname
     * @return User
     */
    public function setUsrFamilyname($usrFamilyname)
    {
        $this->usrFamilyname = $usrFamilyname;

        return $this;
    }

    /**
     * Get usrFamilyname
     *
     * @return string
     */
    public function getUsrFamilyname()
    {
        return $this->usrFamilyname;
    }

    /**
     * Add adr
     *
     * @param Ahs\DemoBundle\Entity\Address $adr
     * @return User
     */
    public function addAdr(\Ahs\DemoBundle\Entity\Address $adr)
    {
        $this->adr[] = $adr;

        return $this;
    }

    /**
     * Remove adr
     *
     * @param Ahs\DemoBundle\Entity\Address $adr
     */
    public function removeAdr(\Ahs\DemoBundle\Entity\Address $adr)
    {
        $this->adr->removeElement($adr);
    }

    /**
     * Get adr
     *
     * @return Doctrine\Common\Collections\Collection
     */
    public function getAdr()
    {
        return $this->adr;
    }

    // NOT GENERATED BY DOCTRINE

    /**
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getEmails()
    {
        return $this->emails;
    }

    /**
     * @param Doctrine\Common\Collections\ArrayCollection $emails
     */
    public function setEmails(ArrayCollection $emails)
    {
        $this->emails = $emails;
    }

    /**
     * @param Ahs\DemoBundle\Entity\Email $email
     * @return User
     */
    public function addEmails(\Ahs\DemoBundle\Entity\Email $email)
    {
        $email->setUsr($this);

        $this->emails[] = $email;

        return $this;
    }
}